name: Update Database CSV
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install cloudscraper beautifulsoup4

      - name: Run Scraper
        run: python the_beast.py

      - name: Commit and Push
        run: |
          git config --global user.name "Auto-Updater"
          git config --global user.email "bot@github.com"
          git add database.csv
          git commit -m "Update series list" || exit 0
          git push
